#version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smartphoneDB
    volumes:
      - mongo-data:/data/db
    networks:
      - fullstack-network

  backend:
    image: espoir10/backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      DELETE_CODE: ${DELETE_CODE}
    depends_on:
      - mongo
    networks:
      - fullstack-network

  frontend:
    image: espoir10/frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - backend
    networks:
      - fullstack-network

volumes:
  mongo-data:

networks:
  fullstack-network:
    driver: bridge
